FROM scratch
EXPOSE 9001
ENTRYPOINT ["/bin/miniconsole"]
CMD ["serve"]
ENV MINIO_ENDPOINT=minio:9000         \
    MINIO_KEY_ID=minioadmin           \
    MINO_ACCESS_KEY=minioadmin        \
    MINIO_SSL="false"                 \
    BIND=:9001                        \
    MAX_OBJECTS="1024"                \
    GIN_MODE=release
ADD miniconsole /bin/
